ARG source_image
FROM ${source_image}
ENV RAILS_ENV=test
COPY --chown=app:app ./spec /home/app/spec
COPY --chown=app:app ./.rspec /home/app/.rspec
COPY --chown=app:app ./.rspec_parallel /home/app/.rspec_parallel
USER root
RUN apt-get update -q && \
    apt-get install -qy tzdata npm --no-install-recommends shared-mime-info && apt-get clean && \
    rm -rf /var/lib/apt/lists/* && rm -fr *Release* *Sources* *Packages* && \
    truncate -s 0 /var/log/*log \

## Add the wait script to the image


USER app
CMD ["sh", "-c", "bundle exec rake db:create db:migrate && bundle exec rspec"]