#!/bin/sh
sleep 1
exec 2>&1
export HOME=/usr/src/app
cd $HOME
# chown -R $WEBUSER:$WEBUSER $HOME
if [ "$RAILS_ENV" = "development" ]; then
  exec chpst -u $WEBUSER bundle exec rails server -P /tmp/server.pid --binding=0.0.0.0
else
  exec chpst -u $WEBUSER bundle exec unicorn
fi
